servers:
  - server: "localhost:2181"
    displayName: zh1
  - server: "192.168.57.102:2181"
    displayName: zh2
  - server: "192.168.57.103:2181"
    displayName: zh3

# The list of commands can be found here http://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_zkCommands

commands:
   - command: "ruok"
   - command: "mntr"
     separator: "\t"
     fields: [
        zk_avg_latency,
        zk_max_latency,
        zk_min_latency,
        zk_packets_received,
        zk_packets_sent,
        zk_num_alive_connections,
        zk_outstanding_requests,
        zk_znode_count,
        zk_watch_count,
        zk_ephemerals_count,
        zk_approximate_data_size,
        zk_followers,                      #only exposed by the Leader
        zk_synced_followers,               #only exposed by the Leader
        zk_pending_syncs,                  #only exposed by the Leader
        zk_open_file_descriptor_count,     #only available on Unix platforms
        zk_max_file_descriptor_count       #only available on Unix platforms
     ]

# Uncomment the following to support additional metrics
#   - command: "stat"
#     separator: ":"
#     fields: [
#        Received,
#        Sent,
#        Outstanding,
#        Node count,
#        Latency min/avg/max
#     ]

metricPrefix:  "Custom Metrics|Zookeeper|"